name: 🐞 Design Bug Report
description: Create a report to help us improve
type: Bug
labels: ["👩‍👧‍👦community feedback"]

body:

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        Use this template for [**Code bugs**](https://github.com/db-ux-design-system/core-web/issues/new?template=bug_report.yaml)
        Please make sure that you are using the **latest version of the tool**. The use of an older version can lead to errors in the components that no longer occur in the current version.

        ⚠️ **Please keep in mind to use anonymous sample material:**
        - **Do not share any personal data (e.g., names, email addresses, customer data)**
        - **Do not attach any confidential company information**
        - **Do not upload full-screen product screenshots**
        - **Do not share internal URLs.**
 
  - type: checkboxes
    id: ds-library
    attributes:
      label: Which design system content is impacted? * (PLEASE SELECT THE LIBRARY)
      description: Select all the ones that apply, to the best of your knowledge.
      options:
        - label: Figma Core Foundations
        - label: Figma Core Components
        - label: Figma Core Patterns
        - label: Figma DB Theme Icons (functional, illustrative)
        - label: Figma 🧪 Core Lab
        - label: Sketch Core (Foundations/Components/Patterns)
        - label: Sketch Core Icons
        - label: Documentation

  - type: input
    id: ds-version
    attributes:
      label: Which version is impacted?
      description: Please let us know which version number is affected.
      placeholder: ex. 3.0.0-Beta-1 or 3.0.13
    validations:
      required: false
      
  - type: textarea
    id: reproduction_fiddle
    attributes:
      description: A clear and concise description of what the bug is. ⚠️ Please also mention the density if you are not working with regular.
      label: Reproduction case
      placeholder: How can we reproduce the error?
    validations:
      required: true

  - type: textarea
    id: expected_behaviour
    attributes:
      description: A clear and concise description of what the bug is.
      label: Expected 
      placeholder: What did you expect to see?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      description: Add screenshots to help explain your problem 💌 or give our design system test account access to your Figma file 👉 db-ux-designsystem@deutschebahn.com
      label: Screenshots
      placeholder: Screenshots often help us to better understand the problem.

  - type: textarea
    id: additional_information
    attributes:
      label: Add any other context about the problem here.
    validations:
      required: false

  - type: dropdown
    id: businessunit
    attributes:
      label: Which DB business unit do you work for?
      options:
        - DB Systel GmbH (please name your customer below)
        - DB Fernverkehr AG
        - DB Regio AG
        - DB InfraGO AG
        - DB Cargo AG
        - DB Konzern
        - DB Vertrieb GmbH
        - DB Energie
        - DB Connect
        - other (please specify below)
    validations:
      required: false

  - type: input
    id: businessunit2
    attributes:
      label: ”DB Systel” please enter your customer / ”other” please enter your area or business unit.
    validations:
      required: false

  - type: input
    id: project
    attributes:
      label: What project are you working on?
    validations:
      required: false
