name: '👩‍👧‍👦 Community Component Contribution'
description: Contribute a new component to be added to Community Components of the DB UX Design System.
labels: ["👩‍👧‍👦community contribution"]
title: '[Beitrag]: '

body:
  - type: markdown
    attributes:
      value: "---"
  - type: markdown
    attributes:
      value: "### 📦 Details zum Beitrag"
  - type: textarea
    id: content-name
    attributes:
      label: Content Name (Kurze Beschreibung)
      placeholder: Hier den Namen/die Beschreibung des Contents einfügen
    validations:
      required: true
  - type: checkboxes
    id: content-type
    attributes:
      label: Content Type
      options:
        - label: Design (Figma)
        - label: Code (Playground)
  - type: markdown
    attributes:
      value: "---"
  - type: markdown
    attributes:
      value: "### 🔗 Links"
  - type: markdown
    attributes:
      value: "For Figma components, please use the following [template](https://www.figma.com/design/J68ecsDtSfB6hsfParlaeQ/Community-Component-Template?node-id=25-420&t=e1vUu9ZE7t0Ij4BZ-1) and save the file with view permissions for the Deutsche Bahn organization in the [DB UX DS - Community Components project](https://www.figma.com/files/1298536054217934978/project/457665083/DB-UX-DS---Community-Components?fuid=1090987523035283074)." 
  - type: textarea
    id: figma-links
    attributes:
      label: Figma Link(s)
      placeholder: "Insert Figma-Link(s)"
  - type: textarea
    id: playground-links
    attributes:
      label: Playground Link(s)
      placeholder: "Insert Playground-Link(s)"
  - type: markdown
    attributes:
      value: "---"
  - type: markdown
    attributes:
      value: "### 📦 Additional information"

  - type: dropdown
    id: businessunit
    attributes:
      label: Geschäftsfeld?
      options:
        - DB Systel GmbH 
        - DB Fernverkehr AG
        - DB Regio AG
        - DB InfraGO AG
        - DB Cargo AG
        - DB Konzern
        - DB Vertrieb GmbH
        - DB Energie
        - DB Connect
        - andere
    validations:
      required: false
