name: 'Contribution: Community Component'
description: Contribute a new component to be added to Community Components / DB UX Design System.
labels: ["👩‍👧‍👦community contribution"]
title: '[Beitrag]: '

body:
  - type: markdown
    attributes:
      value: "### 📦 Details zum Beitrag"
- type: input
    id: component-name
    attributes:
      label: Component Name
      placeholder: "Insert the component name"
  - type: textarea
    id: component-description
    attributes:
      label: Component Description
      placeholder: "Insert a short description of the component"
    validations:
      required: true
  - type: checkboxes
    id: content-type
    attributes:
      label: Content Type
      options:
        - label: Design (Figma)
        - label: Code (Playground)
  - type: markdown
    attributes:
      value: "---"
  - type: markdown
    attributes:
      value: "### 🔗 Links"
  - type: textarea
    id: figma-links
    attributes:
      label: Figma Link(s)
      placeholder: "Hier den/die Figma-Link(s) des Nutzers einfügen."
  - type: textarea
    id: playground-links
    attributes:
      label: Playground Link(s)
      placeholder: "Hier den/die Playground-Link(s) des Nutzers einfügen."
      
  - type: dropdown
    id: businessunit
    attributes:
      label: Geschäftsfeld?
      options:
        - DB Systel GmbH 
        - DB Fernverkehr AG
        - DB Regio AG
        - DB InfraGO AG
        - DB Cargo AG
        - DB Konzern
        - DB Vertrieb GmbH
        - DB Energie
        - DB Connect
        - andere
    validations:
      required: false
