name: ✨ Feature request
description: Request a new feature to be added to DB UX Design System.
labels: ["👩‍👧‍👦community feedback"]
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue! Use this template if you want to request a new feature, or a change to an existing feature.
        If you are reporting a bug or problem, please use the bug template instead.
        
        📣 Please create a separate issue for each feature.
  
  - type: dropdown
    id: businessunit
    attributes:
      label: Which DB business unit do you work for?
      options:
        - DB Systel GmbH
        - DB Fernverkehr AG
        - DB Regio AG
        - DB InfraGO AG
        - DB Konzern
        - DB Cargo AG
        - DB Vertrieb GmbH
        - DB Energie
        - DB Connect
        - other (please specify below)
    validations:
      required: false

  - type: input
    id: businessunit2
    attributes:
      label: ”DB Systel” please enter your customer / ”other” please enter your area or business unit.
    validations:
      required: false
      
  - type: input
    id: project
    attributes:
      label: What project are you working on?
    validations:
      required: false   
  
  - type: textarea
    id: description
    attributes:
      description: Give a clear and precise description of the new feature. If possible, be sure to include examples, screenshots or videos to illustrate your request.
      label: Description
      placeholder: 
    validations:
      required: true
