name: Epic (for Core Team only)
description: Template for Core Team
labels: [version3]
type: Epic
body:
  - type: markdown
    attributes:
      value: |
        _Dieses Issue dient als zentrale Sammelstelle für die Entwicklung der Tag Komponente._

        ⚠️ **Please keep in mind to use anonymous sample material:**
        - **Do not share any personal data (e.g., names, email addresses, customer data)**
        - **Do not attach any confidential company information**
        - **Do not upload full-screen product screenshots**
        - **Do not share internal URLs.**
        
        ---
  
  - type: textarea
    id: description
    attributes:
      description: Give a clear and precise description of the new feature. If possible, be sure to include examples, screenshots or videos to illustrate your request.
      label: Description
      placeholder: 
    validations:
      required: true

  - type: textarea
    id: goal
    attributes:
      description: Give a clear and precise description of the goal of this epic.
      label: Goal
      placeholder: 
      value: "This epic covers all tasks related to the conception, design development, implementation, documentation, quality assurance, and publication of the [component name] component for the DB UX design system. The goal is to create a consistent, accessible and documented component that is available to DS users in the production system."
    validations:
      required: true

  - type: textarea
    id: showcase
    attributes:
      description: URL of the Showcase
      label: Description
      placeholder: https://design-system.deutschebahn.com/core-web/review/main/components/tag/overview
    validations:
      required: false

  - type: textarea
    id: figma
    attributes:
      description: URL of the Figma file
      label: Figma
      placeholder: 
    validations:
      required: false


  - type: textarea
    id: documentation
    attributes:
      description: URL of the Documentation
      label: Documentation
      placeholder: 
    validations:
      required: false

  - type: textarea
    id: tags
    attributes:
      description: Alternative names
      label: 🏷️      
      placeholder: 
    validations:
      required: false
